from . import views
from django.urls import path

urlpatterns = [
    path("", views.api_info, name="index"),
    path("api/health/", views.health_api, name="health_api"),
    path("api/auth/me/", views.me_api, name="me_api"),
    path("api/auth/login/", views.login_api, name="login_api"),
    path("api/auth/logout/", views.logout_api, name="logout_api"),
    path("api/auth/register/", views.register_api, name="register_api"),
    path("api/profile/me/", views.my_profile_api, name="my_profile_api"),
    path("api/developers/", views.developers_api, name="developers_api"),
    path("api/developers/<str:username>/", views.developer_detail_api, name="developer_detail_api"),
    path("api/projects/", views.projects_api, name="projects_api"),
    path("api/projects/<slug:slug>/", views.project_detail_api, name="project_detail_api"),
    path("api/projects/<slug:slug>/publish/", views.publish_project_api, name="publish_project_api"),
    path("api/projects/<slug:slug>/archive/", views.archive_project_api, name="archive_project_api"),
    path("api/projects/<slug:slug>/join/", views.join_project_api, name="join_project_api"),
    path("api/projects/<slug:slug>/apply/", views.apply_project_api, name="apply_project_api"),
    path("api/projects/<slug:slug>/roles/<int:role_id>/apply/", views.apply_project_api, name="apply_role_api"),
    path("api/projects/<slug:slug>/members/", views.project_members_api, name="project_members_api"),
    path("api/projects/<slug:slug>/invite/", views.invite_to_project_api, name="invite_to_project_api"),
    path("api/memberships/", views.my_memberships_api, name="my_memberships_api"),
    path("api/dashboard/", views.dashboard_api, name="dashboard_api"),
    path("api/dashboard/projects/", views.dashboard_projects_api, name="dashboard_projects_api"),
    path("api/activity/", views.activity_api, name="activity_api"),
    path("api/recommendations/", views.recommendations_api, name="recommendations_api"),
    path("api/notifications/", views.notifications_api, name="notifications_api"),
    path("api/notifications/mark-all-read/", views.mark_all_notifications_read_api, name="mark_all_notifications_read_api"),
    path("api/notifications/<int:notification_id>/", views.notification_detail_api, name="notification_detail_api"),
    path("api/preferences/", views.preferences_api, name="preferences_api"),
    path("api/applications/", views.applications_api, name="applications_api"),
    path("api/applications/sent/", lambda request: views.applications_api(request, "sent"), name="sent_applications_api"),
    path("api/applications/received/", lambda request: views.applications_api(request, "received"), name="received_applications_api"),
    path("api/applications/<int:application_id>/", views.application_detail_api, name="application_detail_api"),
    path("api/applications/<int:application_id>/withdraw/", views.withdraw_application_api, name="withdraw_application_api"),
    path("api/applications/<int:application_id>/accept/", views.accept_application_api, name="accept_application_api"),
    path("api/applications/<int:application_id>/reject/", views.reject_application_api, name="reject_application_api"),
]
